Require Export GeoCoq.Tarski_dev.Ch03_bet.Ch03_bet.
Require Export GeoCoq.Tarski_dev.Ch03_bet.Ch03_bet_l2_11.
Require Export GeoCoq.Tarski_dev.Ch03_bet.Ch03_bet_not.
Require Export GeoCoq.Tarski_dev.Ch03_bet.Ch03_bet_eq.
Require Export GeoCoq.Tarski_dev.Ch03_bet.Ch03_bet_diff.
Require Export GeoCoq.Tarski_dev.Ch03_bet.Ch03_bet_transitivity.
Require Export GeoCoq.Tarski_dev.Ch03_bet.Ch03_exists.
Require Export GeoCoq.Tarski_dev.Ch03_bet.Ch03_OFSC.
Require Export GeoCoq.Tarski_dev.Ch03_bet.Ch03_IFSC.
Require Export GeoCoq.Tarski_dev.Ch03_bet.bet4.Ch03_bet4.
Require Export GeoCoq.Tarski_dev.Ch03_bet.bet4.Ch03_bet4_bet.
Require Export GeoCoq.Tarski_dev.Ch03_bet.bet4.Ch03_bet4_eq.
Require Export GeoCoq.Tarski_dev.Ch03_bet.bet4.Ch03_bet4_exists.
Require Export GeoCoq.Tarski_dev.Ch03_bet.bet4.Ch03_bet4_l2_11.
Require Export GeoCoq.Tarski_dev.Ch03_bet.bet5.Ch03_bet5.
Require Export GeoCoq.Tarski_dev.Ch03_bet.bet5.Ch03_bet5_l2_11.
Require Export GeoCoq.Tarski_dev.Ch03_bet.Ch03_bet_cong3.
Require Export GeoCoq.Tarski_dev.Ch03_bet.bet4.Ch03_bet4_cong4.
Require Export GeoCoq.Tarski_dev.Ch03_bet.Ch03_QEqui.
Require Export GeoCoq.Tarski_dev.Ch03_bet.Ch03_bet_cases.
Require Export GeoCoq.Tarski_dev.Ch03_bet.Ch03_bet_cong_eq.
Require Export GeoCoq.Tarski_dev.Ch03_bet.Ch03_decidability.
(* Require Export GeoCoq.Tarski_dev.Ch03_bet.Ch03_tactics. *)
(*Require Export GeoCoq.Tarski_dev.Ch03_bet.Ch03_stability.*)